apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: my-tier
  template:
    metadata:
      labels:
        tier: my-tier
    spec:
      containers:
      - name: my-container
        image: zelic91/users@latest