DATABASE_URL := $(shell grep POSTGRES_URL= .env | sed 's/POSTGRES_URL=//')

init:
	go mod tidy
	go get -u github.com/spf13/cobra@latest
	go get -u github.com/spf13/viper
	mv env.example .env
	mv gitignore .gitignore

dep:
	brew install dbmate
	go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
	go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest

migrate:
	dbmate -u $(DATABASE_URL) -d ./db/postgres/migrations -s ./db/postgres/schema.sql up

apigen:
	rm -rf api/gen
	mkdir api/gen
	oapi-codegen -package gen api/openapi.yaml > api/gen/spec.gen.go

dbgen_mongo:
{{- range $serviceName, $service := $.Services }}
	{{- range $serviceName2, $database := $.ServiceDatabaseMap }}
		{{- if and (eq $serviceName $serviceName2) (eq .Type "mongo") }}
	repogen -pkg={{ $serviceName | singularize | lower }} -dest={{ $serviceName | singularize | lower }}/repo.go \
			-model={{ $service.Model | singularize | title }} -repo=Repo
		{{- end }}
	{{- end }}
{{- end }}

dbgen_postgres:
	rm -rf db/postgres/dbgen
	sqlc -f db/postgres/sqlc.config.yaml generate

gen: apigen dbgen_mongo dbgen_postgres
	go mod tidy

{{- range $commandName, $command := .Commands }}
{{ $commandName }}:
	go run main.go {{ $commandName }}
{{- end }}

docker:
	docker image rm {{ .ModuleName }} & \
	docker build -t {{ .ModuleName }} . && \
	docker run --rm \
		--env-file ./.env.docker \
		-p 3000:3000 \
		--name {{ .ModuleName }} {{ .ModuleName }}


.PHONY: init dev prepdev apigen toolsup toolsdown gen docker dbgen_mongo dbgen_postgres