version: '3.5'

services:
  mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - backend
    ports:
      - '27017:27017'
    volumes:
      - db:/mongodata/db
volumes:
  db:
networks:
  backend:
    name: backend
